apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: client
    protocol: TCP
  - port: 16379
    targetPort: 16379
    name: bus
  selector:
    app: redis
